version: '3.7'

services:
  web:
    build: .
    command: gunicorn vife_project.wsgi -b 0.0.0.0:8000
    env_file: .env.prod
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    env_file: .env.db
